version: '2.4'

services:
  application:
    build:
      context: '.'
      dockerfile: testing.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - MYSQL_URL=mysql://user:TB5e8EuFSxEpUFES@database:3306/blog
    command: sleep 10000
  
  database:
    image: mysql:5.7.10
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-u", "user", "-pTB5e8EuFSxEpUFES" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=YmW4TG96RnutHRba
      - MYSQL_DATABASE=blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=TB5e8EuFSxEpUFES
